[tool.poetry]
name = "tradingview-screener"
version = "0.1.0"
description = ""
authors = ["shner-elmo <770elmo@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "tradingview_screener"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"
pandas = "^2.0.1"

[tool.poetry.group.dev.dependencies]
ipython = "^8.12.0"
twine = "^4.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
