name: website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Run `pdoc` on branch master
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          poetry run pdoc tradingview_screener/ -o /tmp/docs -t templates/

      - uses: actions/checkout@v4
        with:
          ref: docs
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Move generated docs from temp directory to branch `docs`, and commit (branch docs contains a folder named docs)
        run: |
          mkdir -p ./docs/dev
          cp -r /tmp/docs/* ./docs/dev
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git status
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -a -m "Generated docs for latest dev version"
            git push
          else
            echo "No changes"
          fi          
